# blank_issues_enabled: false
contact_links:
    - name: Request a Feature
      url: https://github.com/notaapp/nota/discussions/categories/feature-requests
      about: Share ideas for new features
    - name: Ask a Question
      url: https://github.com/notaapp/nota/discussions/categories/questions
      about: Ask the community for help
